Repository jewonzzzzz/project_Unicon_R1.0, pull requests merged in 2024-11, with the labels that each got.

#14 커뮤니티 관련 파일 추가
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/community/community.jsp
Labels: good first issue

#25 관리자-템플릿-색상수정
  Unicon_r1/src/main/webapp/resources/admin/css/style.css
Labels: 디자인

#32 서버실행오류임시해결
  Unicon_r1/pom.xml
  Unicon_r1/src/main/java/com/Unicon/controller/NoticeController.java
  Unicon_r1/src/main/java/com/Unicon/service/NoticeFileServiceImpl.java
  Unicon_r1/src/main/java/com/Unicon/service/NoticeServiceImpl.java
  Unicon_r1/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  Unicon_r1/src/main/webapp/WEB-INF/spring/root-context.xml
  Unicon_r1/src/main/webapp/WEB-INF/spring/security-context.xml
  Unicon_r1/src/main/webapp/WEB-INF/web.xml
Labels: bug

#42 커뮤니티 - 화면 작업중
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/community/community.jsp
Labels: good first issue

#50 입양VO클래스-생성
  Unicon_r1/src/main/java/com/Unicon/domain/AdptCounselVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/AdptMemberVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/AdptVO.java
Labels: 기능구현

#69 커뮤니티 VO 생성
  Unicon_r1/src/main/java/com/Unicon/domain/CommentLikeVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/CommentVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/FollowVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/ImageVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/JypMemberVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/MyPetVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/PetDataVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/PostLikeVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/PostVO.java
Labels: good first issue

#71 입양글등록기능-데이터입력확인
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/AdptHealthVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/AdptInterestVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/AdptVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/AdptVaccineVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/adptmgmt_main.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/inc/admin_sidebar_adpt.jsp
Labels: 기능구현

#74 Transactional-트랜잭션-관리를 위한-의존성추가, Spring-tx-빈-생성
  Unicon_r1/pom.xml
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/webapp/WEB-INF/spring/root-context.xml
Labels: 기능구현

#76 커뮤니티 mapper 파일 생성
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
Labels: good first issue

#97 커뮤니티 dao / service만 생성
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
Labels: good first issue

#101 커뮤니티 게시물 등록 기능
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/PostVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
Labels: good first issue

#120 유기동물-입양글-등록기능-디자인-구성-및-자바스크립트-일부작성, 검색드롭다운-ajax작성중
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/controller/PetRestController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/writings/insert.jsp
Labels: 디자인, 기능구현

#130 커뮤니티 게시물 등록 기능 3
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_template.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_template_insert.jsp
Labels: good first issue

#137 petData이름변경,등록페이지-작업진행중
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/controller/PetDataRestController.java
  Unicon_r1/src/main/java/com/Unicon/controller/PetRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/CategoryDataVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/PetDataVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CategoryDataDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/java/com/Unicon/service/CategoryDataService.java
  Unicon_r1/src/main/resources/mappers/categoryDataMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/writings/insert.jsp
Labels: 디자인, 기능구현

#138 커뮤니티 게시물 등록 기능 4
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
Labels: good first issue

#140 petdata 이름 수정 완료
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
Labels: good first issue

#156 CategoryDataVO-오타-수정
  Unicon_r1/src/main/java/com/Unicon/domain/CategoryDataVO.java
Labels: 디자인, 기능구현

#159 커뮤니티 게시물 등록 기능 6 (11/26)
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
Labels: good first issue

#169 입양글-동물-데이터분리,VO-DAO-Service수정,매퍼수정진행
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/controller/PetDataRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/AdptCounselVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/AdptVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/AnimalHealthVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/AnimalInterestVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/AnimalVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/AnimalVaccineVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/insert.jsp
Labels: 디자인, 기능구현

#170 커뮤니티 게시물 등록 기능 7 (11/26)
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
Labels: good first issue

#177 매퍼파일수정,메서드수정,서버실행확인
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/controller/PetDataRestController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CategoryDataDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/java/com/Unicon/service/CategoryDataService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/resources/mappers/categoryDataMapper.xml
Labels: 디자인, 기능구현

#190 입양동물등록-페이지-구현-진행중
  Unicon_r1/src/main/java/com/Unicon/domain/AnimalVO.java
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/insert.jsp
  Unicon_r1/src/main/webapp/resources/admin/css/style.css
Labels: 디자인, 기능구현

#191 커뮤니티 게시물 등록 기능 8 (11/27)
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/PostVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
Labels: good first issue

#200 동물성격-입력기능-구현준비
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/insert.jsp
Labels: 디자인, 기능구현

#217 유기동물-등록기능-구현-1차완료
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/AnimalVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/insert.jsp
  Unicon_r1/src/main/webapp/uploads/fourLeafClover.jpg
Labels: 디자인, 기능구현

#221 커뮤니티 게시물 등록 기능 9 (11/28)
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/PostVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
Labels: good first issue

#226 커뮤니티 게시물 등록 기능 10 (11/28)
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/PostVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
Labels: good first issue

#227 이름자동짓기-준비
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
Labels: 디자인, 기능구현

#243 이름자동짓기-구현완료
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/insert.jsp
Labels: 디자인, 기능구현

#244 커뮤니티 게시물 등록 기능 11 + 커뮤니티 모달 화면 구상중 1 (11/29)
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
Labels: good first issue

#248 동물id-유효성검사(DB)-구현완료
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
Labels: 기능구현

#252 동물나이선택-드롭박스구현
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/inc/admin_navbar_adpt.jsp
Labels: 디자인, 기능구현
