Repository jewonzzzzz/project_Unicon_R1.0, pull requests merged in 2024-12, with the labels that each got.

#266 입양동물-등록기능-구현완료
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/controller/TestController.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/insert.jsp
Labels: 디자인, 기능구현

#270 커뮤니티 게시물 등록기능 12 + 커뮤니티 모달 화면 구상중 2 (12/2)
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
Labels: good first issue

#279 매퍼작성,DAO작성,Service작성
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
Labels: 기능구현

#300 컨트롤러-매핑수정, 동물-목록-뷰페이지-일부-구현
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/AnimalVO.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/read.jsp
Labels: 디자인, 기능구현

#303 커뮤니티 등록시 이미지 기능 수정 완료
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
Labels: good first issue

#309 커뮤니티 등록시 이미지 기능 수정 2 완료 (등록 기능 멤버 테이블 연동 제외 완료)
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
Labels: good first issue

#329 Controller, Service, DAO-작성완료
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/AdptMemberVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/read.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/update.jsp
  Unicon_r1/src/main/webapp/resources/admin/images/pawbrownopacity10.png
  Unicon_r1/src/main/webapp/resources/admin/images/pawgreen.png
  Unicon_r1/src/main/webapp/resources/admin/images/pawgreenopacity10.png
  Unicon_r1/src/main/webapp/resources/admin/images/pawgreenopacity15.png
Labels: 디자인, 기능구현

#330 커뮤니티 팔로워, 팔로잉 모달 화면 및 커뮤니티 관련 페이지 화면 구상 완료 (12/3)
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_profile.jsp
Labels: good first issue

#338 매퍼-쿼리-작성,ajax데이터-반환-확인,주소-동물id-유효성-검증-구현
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/update.jsp
Labels: 기능구현

#353 수정페이지-데이터입력-구현완료, 수정시-이미지-제어-수정중
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/PetDataRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/AnimalVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/CategoryDataVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/CheckImageVO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/java/com/Unicon/service/CategoryDataService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/update.jsp
  Unicon_r1/src/main/webapp/WEB-INF/web.xml
Labels: 디자인, 기능구현

#359 수정페이지-이미지-제어기능-구현완료
  Unicon_r1/src/main/java/com/Unicon/domain/CheckImageVO.java
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/update.jsp
Labels: 기능구현

#364 유기동물-정보수정-이미지파일-제어-오류-수정완료
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/update.jsp
Labels: 기능구현

#376 동물정보-수정기능-구현중
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/controller/TestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/CheckImageVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/read.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/update.jsp
Labels: 기능구현

#377 커뮤니티 게시물 조회 기능 구현중 2 -> 완료 / 커뮤니티 해당 게시물 및 해당 게시물 댓글 조회 기능 구현중 1 (12/5)
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/java/com/Unicon/domain/CommentLikeVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/CommentVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/PostLikeVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/PostVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
Labels: good first issue

#381 매퍼,DAO-일부수정
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
Labels: 기능구현

#384 커뮤니티 해당 게시물 및 해당 게시물 댓글 조회 기능 구현중 2 (12/6)
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/PostVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_profile.jsp
Labels: good first issue

#394 커뮤니티 해당 게시물 및 해당 게시물 댓글 조회 기능 구현 완료 (12/6)
  Unicon_r1/src/main/java/com/Unicon/domain/CommentVO.java
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
  Unicon_r1/src/main/webapp/uploads/noImg.png
  Unicon_r1/src/main/webapp/uploads/profileImg.jpg
  Unicon_r1/src/main/webapp/uploads/profileImgMan.jpg
  Unicon_r1/src/main/webapp/uploads/profileImgWoman.jpg
Labels: good first issue

#397 이미지-수정-조건제어-1차-구현완료
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/AnimalVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/debugCheck.txt
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/update.jsp
Labels: 디자인, 기능구현

#412 255 mbti테스트 만들기
  Unicon_r1/src/main/java/com/Unicon/controller/MBTITestController.java
  Unicon_r1/src/main/java/com/Unicon/mbtitest/MBTITest.java
  Unicon_r1/src/main/webapp/WEB-INF/views/mbti/result.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/mbti/start.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/mbti/test.jsp
Labels: good first issue

#423 커뮤니티 게시물 삭제 기능 구현 완료 (12/9)
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
Labels: good first issue

#424 419 지점별 지도 만들기
  Unicon_r1/src/main/java/com/Unicon/controller/MapController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/map/map.jsp
Labels: good first issue

#432 동물정보-수정-및-삭제-구현완료, 동물상태-종료변경-구현완료
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/AnimalVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/read.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/update.jsp
Labels: 디자인, 기능구현

#441 입양글-등록기능-뷰페이지구현-매퍼작성중
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/AdptVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/animalinsert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/animalread.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/animalupdate.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/writings/writinginsert.jsp
  Unicon_r1/src/main/webapp/resources/admin/css/style.css
Labels: 디자인, 기능구현

#444 커뮤니티 게시물 좋아요 기능 구현 완료, 댓글 좋아요 기능 구현중 (12/9)
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/CommentVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
Labels: good first issue

#446 입양글id-생성기능-구현중
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
Labels: 디자인, 기능구현

#453 지도 디비 연결
  Unicon_r1/src/main/java/com/Unicon/controller/MapController.java
  Unicon_r1/src/main/java/com/Unicon/domain/MapVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/MapDAO.java
  Unicon_r1/src/main/webapp/WEB-INF/views/map/map.jsp
Labels: good first issue

#462 입양글-등록기능-구현완료
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/AdptCounselVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/AdptVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/AnimalVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/animalread.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/animalupdate.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/writings/writinginsert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/inc/admin_sidebar_adpt.jsp
Labels: 디자인, 기능구현

#469 커뮤니티 종류별 매핑 처리 완료 / select태그 별 정렬 기능 구현중
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
Labels: good first issue

#481 지도 3차 완료
  Unicon_r1/src/main/java/com/Unicon/controller/MapController.java
  Unicon_r1/src/main/java/com/Unicon/domain/MapVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/MapDAO.java
  Unicon_r1/src/main/resources/mappers/Map.Mapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/map/map.jsp
Labels: good first issue

#489 종류 눌렀을시 오류 수정 / 커뮤니티 게시물 수정 기능 구현중 1
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
  Unicon_r1/src/main/webapp/resources/new_assets/js/jjj.js
Labels: good first issue

#492 입양글-수정기능-삭제기능-구현, 입양글-승인기능-구현중
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/animal_add.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/animal_read.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/animal_update.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/manager/manager_writing_read.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/manager/manger_writing_update.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/writings/writing_add.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/writings/writing_read.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/writings/writing_update.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/inc/admin_sidebar_adpt.jsp
Labels: 디자인, 기능구현

#497 목록페이지-아이디설정중
  Unicon_r1/src/main/java/com/Unicon/controller/AdptRestController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
Labels: 디자인, 기능구현

#508 커뮤니티 게시물 수정 기능 구현중 2 (12/13)
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/PostVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_update.jsp
Labels: good first issue

#510 입양글-승인취소-완료, 메인페이지용-매퍼작성-DAO-Service-작성
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/manager/manager_writing_read.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/manager/manager_writing_update.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/writings/writing_read.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/writings/writing_update.jsp
Labels: 디자인, 기능구현

#512 입양글-승인상태-조건추가
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/animal_add.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/writings/writing_add.jsp
Labels: enhancement

#515 메인페이지용 커뮤니티 매퍼 dao service 작성 (맨 윗부분)
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
Labels: good first issue

#520 사용자페이지-입양글-목록-구현완료, 모달-구현준비
  Unicon_r1/src/main/java/com/Unicon/controller/AdptController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtRestController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adpt/adpt_list.jsp
  Unicon_r1/src/main/webapp/resources/new_assets/js/adpt.js
  Unicon_r1/src/main/webapp/uploads/defaultAdpt.jpg
Labels: 디자인, 기능구현

#524 커뮤니티 게시물 수정 및 삭제 응급조치 완료 / 게시물 상태별 검색, 더보기버튼 진행중 (12/15)
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
Labels: good first issue

#527 지도 4차 완료
  Unicon_r1/src/main/java/com/Unicon/controller/MBTITestController.java
  Unicon_r1/src/main/java/com/Unicon/controller/MapController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/map/map.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/mbti/result.jsp
Labels: good first issue

#529 입양글-목록-모달완료, 필터링-추가기능과-상담신청-기능-우선순위고민,
  Unicon_r1/src/main/java/com/Unicon/controller/AdptController.java
  Unicon_r1/src/main/java/com/Unicon/domain/AnimalVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adpt/adpt_list.jsp
  Unicon_r1/src/main/webapp/resources/new_assets/js/adpt.js
Labels: 디자인, 기능구현

#531 커뮤니티 게시물 종류 선택시 오류 수정
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
  Unicon_r1/src/main/webapp/resources/new_assets/js/jjj.js
Labels: good first issue

#533 커뮤니티 게시물 더보기 버튼 기능 구현 완료/swal.fire 전 기능 추가 완료/커뮤니티 지역 컬럼 추가/필터 작업중 1
  Unicon_r1/src/main/java/com/Unicon/domain/PostVO.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_update.jsp
  Unicon_r1/src/main/webapp/resources/new_assets/js/jjj.js
Labels: good first issue

#542 모달이미지-변경, 이전글, 모달페이지-구성-변경
  Unicon_r1/src/main/java/com/Unicon/controller/AdptController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adpt/adpt_list.jsp
  Unicon_r1/src/main/webapp/resources/new_assets/js/adpt.js
Labels: 디자인, 기능구현

#544 매퍼수정
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
Labels: bug

#548 커뮤니티 전체 게시물 페이지 필터 및 검색 구현 완료/메인페이지용 서비스 구현 완료/댓글 오류 수정중
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/java/com/Unicon/domain/CommentVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/PostVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_profile.jsp
  Unicon_r1/src/main/webapp/resources/new_assets/js/jjj.js
Labels: good first issue

#559 댓글 오류 수정완료/프로필 이미지 눌렀을때 프로필로 이동 구현 완료
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_profile.jsp
Labels: good first issue

#564 상담신청-상담버튼제어
  Unicon_r1/src/main/java/com/Unicon/controller/AdptController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adpt/adpt_list.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/animal_update.jsp
  Unicon_r1/src/main/webapp/resources/new_assets/js/adpt.js
Labels: 디자인, 기능구현

#571 커뮤니티 페이지 로그인한 아이디 세션 값 불러오기 완료 / 불필요 파일 정리 완료
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/community/community.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_profile.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_template.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_template_insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_update.jsp
Labels: good first issue

#574 상담신청페이지-작업중
  Unicon_r1/src/main/java/com/Unicon/controller/AdptController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtController.java
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtRestController.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/counsel_read.jsp
Labels: 디자인, 기능구현

#580 매퍼작성
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/resources/new_assets/js/adpt.js
Labels: 디자인, 기능구현

#581 상황별로 버튼제어 안보이게/alert창 수정/프로필이미지추가중/헤더에 이동할수 있게/매핑 변경/프로필에서 반려동물 확인가능
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityController.java
  Unicon_r1/src/main/java/com/Unicon/controller/CommunityRestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/MemberVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/PetVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/PostVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
  Unicon_r1/src/main/resources/mappers/communityMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/community/main.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_profile.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_update.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/inc/new_header.jsp
Labels: good first issue

#591 입양글 이미지 처리 및 맵 수정
  Unicon_r1/src/main/java/com/Unicon/controller/MBTITestController.java
  Unicon_r1/src/main/java/com/Unicon/domain/MapVO.java
  Unicon_r1/src/main/java/com/Unicon/domain/PetAdoptionVO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/MapDAO.java
  Unicon_r1/src/main/java/com/Unicon/persistence/PetAdoptionDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/PetAdoptionService.java
  Unicon_r1/src/main/resources/mappers/Map.Mapper.xml
  Unicon_r1/src/main/resources/mappers/PetAdoptionMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/mbti/result.jsp
Labels: good first issue

#605 mbti 결과수정
  Unicon_r1/src/main/webapp/WEB-INF/views/mbti/result.jsp
Labels: good first issue

#610 댓글 등록시 비로그인이면 로그인 페이지로 이동/불필요 주석 삭제, 콘솔로그 주석/마지막 오류 점검
  Unicon_r1/src/main/java/com/Unicon/persistence/CommunityDAO.java
  Unicon_r1/src/main/webapp/WEB-INF/views/community/mypage.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_insert.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_list.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_profile.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/community/new_update.jsp
  Unicon_r1/src/main/webapp/resources/new_assets/js/jjj.js
Labels: good first issue

#619 수정완료
  Unicon_r1/src/main/webapp/WEB-INF/views/map/map.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/mbti/result.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/mbti/start.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/mbti/test.jsp
Labels: good first issue

#623 로그인,로그아웃-플러터-정보전송
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtRestController.java
  Unicon_r1/src/main/webapp/WEB-INF/views/main/new_main.jsp
Labels: 디자인, 기능구현

#629 마이페이지-로그아웃처리
  Unicon_r1/src/main/webapp/WEB-INF/views/mypage/main.jsp
Labels: 디자인, 기능구현

#644 이미지경로수정
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/counsel_read.jsp
Labels: bug

#645 이미지 수정 기능 테스트
  Unicon_r1/src/main/java/com/Unicon/service/CommunityService.java
Labels: good first issue

#649 이미지-경로-수정
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
Labels: bug

#655 신청기능-모달구현중
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/counsel_read.jsp
Labels: 디자인, 기능구현

#660 상담신청-승인완료,입양완료-기능구현
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtRestController.java
  Unicon_r1/src/main/java/com/Unicon/persistence/AdptDAO.java
  Unicon_r1/src/main/java/com/Unicon/service/AdptService.java
  Unicon_r1/src/main/resources/mappers/adptMapper.xml
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/animal_update.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/adptmgmt/animals/counsel_read.jsp
Labels: 디자인, 기능구현

#698 제어조건-수정
  Unicon_r1/src/main/java/com/Unicon/controller/AdptMgmtRestController.java
Labels: 디자인, 기능구현

#700 로고변경-및-사이드바-메뉴수정
  Unicon_r1/src/main/webapp/WEB-INF/views/inc/admin_navbar_adpt.jsp
  Unicon_r1/src/main/webapp/WEB-INF/views/inc/admin_sidebar_adpt.jsp
  Unicon_r1/src/main/webapp/resources/admin/images/pawbrownopacity10.png
  Unicon_r1/src/main/webapp/resources/admin/images/pawgreen.png
  Unicon_r1/src/main/webapp/resources/admin/images/pawgreenopacity10.png
  Unicon_r1/src/main/webapp/resources/admin/images/pawgreenopacity15.png
  Unicon_r1/src/main/webapp/resources/admin/images/unicon_logo_15025.png
  Unicon_r1/src/main/webapp/resources/admin/images/unicorn_logo_mini.png
Labels: bug

#702 form.jsp-misc.js파일-스크립트-로드
  Unicon_r1/src/main/webapp/WEB-INF/views/notice/manage/form.jsp
Labels: enhancement
